#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/app
frontend_repo: "https://github.com/Ibrahim-Gamal-Ibrahim/my_scripts.git"
frontend_version: "main"

repo_tmp_dir: /tmp/frontend
frontend_tmp_dir: /tmp/frontend/projects/Deploy_simple_Nginx_web_on_AWS
#reposatory_tmp_dir: /tmp/frontend
nginx_root: /var/www/app

frontend_owner: www-data
frontend_group: www-data
